apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadrenc8006-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadrenc8006-tenant-component
    app.kubernetes.io/part-of: loadrenc8006-tenant-app
  name: loadrenc8006-tenant-component
  namespace: loadrenc8006-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadrenc8006-tenant-component
    weight: null
status: {}
